### ISSUE TITLE
Nice app @aaronmcleacs!

### ISSUE THREAD

**Issue by daley-mottley** [aaronmcleancs/RepBook-DemoServer#1]
Hey @aaronmcleancs, the app you've built looks really nice. I look forward to trying it out for myself 😁

**Comment by aaronmcleancs** [comment]
> Hey @aaronmcleancs, the app you've built looks really nice. I look forward to trying it out for myself 😁

Thanks Daley! Far from finished but it's a good template for user auth with a frontend. Let me know if you have any issues getting it running.
